### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by freopt** [gigabit101/QuantumStorage#179] opened 2019-01-05 00:06 UTC
I placed a unit and this happened. Latest mod version. Forge 14.23.5.2782
https://paste.dimdev.org/volosimebu.mccrash

EDIT:
It was when opening the gui. This happened when using the tank aswell.

**Comment by K-Hyouma** [comment] 2019-01-05 06:52
Hello.
I also encountered a similar crash.
My friend told me that updating the "RebornCore" version is a problem.
I tried using "RebornCore-1.12.2-3.12.1.385" and it worked.

The cause was in changing the method name.
In RebornCore's GUIBuilder, "isInRect" was changed to "isPointInRect".

**Comment by gigabit101** [comment] 2019-01-12 00:20
fixed in 4.6.5

**Closed as completed by gigabit101** 2019-01-12 00:20 UTC
