### ISSUE TITLE
Quantum Tank Duplication

### ISSUE THREAD

**Issue by Furionstrom** [gigabit101/QuantumStorage#171] opened 2018-12-08 19:40 UTC
When placing a quantum storage tank to the south of an Extra Utilities 2 Transfer Pipe the tank will be placed but remains in your inventory. (need to sort inventory or access tank GUI for it to appear in inventory).  Duplication only appears to occur when placing the tank on the pipe.  If the pipe is placed on the tank the duplication does not occur. 

Quantum Storage 4.6.2

**Comment by Furionstrom** [comment] 2018-12-08 19:47
This same thing also occurs with Quantum storage units

**Comment by gigabit101** [comment] 2018-12-09 01:40
Dupe of #165

**Closed as completed by gigabit101** 2018-12-09 01:40 UTC
