### ISSUE TITLE
Items disappear on shift-click to fill an itemstack

### ISSUE THREAD

**Issue by AMartinie** [gigabit101/QuantumStorage#122] opened 2017-12-17 21:50 UTC
Easy recreation on my end. (Modpack ATM3 v5.4)
Shift-clicking an itemstack from your inventory into iron,gold, or diamond storage crates will fill the current stack in the crate and null the rest of the items.

MC version 1.12.2
Forge 14.23.1.2562

**Comment by CursedFlames** [comment] 2017-12-25 21:56
This also seems to happen when shift-clicking items out of a Quantum Storage Unit, if there is a partial stack of the item it will take 64 from the QSU but only fill that partial stack.

**Comment by gigabit101** [comment] 2017-12-27 13:35
@modmuss50 did you break the shift click code in RC again?

**Comment by modmuss50** [comment] 2017-12-27 14:05
Uhh, I could have done. You use RebornContianer right?

**Comment by gigabit101** [comment] 2017-12-27 14:16
yup

**Comment by BaccarWozat** [comment] 2018-01-01 08:06
For those wondering, the recent release of RebornCore (3.6.1.183) has been tested and does not fix this issue.
EDIT: Also 3.6.2.187, 3.6.4.194...
EDIT2: Fixed in latest compiled RebornCore. Thanks CursedFlames!

**Comment by gigabit101** [comment] 2018-01-01 15:36
I have been away for the last 10 days so I have not been able to look into this

**Comment by CursedFlames** [comment] 2018-01-11 03:30
Haven't tested it, but it looks like this issue might be caused by [this line in the shiftItemStack method](https://github.com/TechReborn/RebornCore/blob/5495dbd819daba5f829c151dba2c1c0caee27603/src/main/java/reborncore/common/container/RebornContainer.java#L173). The itemstack count seems to be  set to a negative, which presumably empties the itemstack.

**Comment by CursedFlames** [comment] 2018-02-02 23:30
This should be fixed with the next RebornCore update.

**Comment by gigabit101** [comment] 2018-02-03 20:54
Yup

**Closed as completed** 2018-02-19 00:53 UTC
