### ISSUE TITLE
Game crash when adding fluid to RS system with quantum fluid disk

### ISSUE THREAD

**Issue by dlevack** [gigabit101/QuantumStorage#157] opened 2018-08-08 07:43 UTC
Version 4.6.1 Quantum Storage
Version 1.6.3 Refined Storage
Works fine with the RS fluid disk but once I change it to the quantum fluid disk it crashes the second I set an importer to fluid mode and I have to recreate the world:

[07:36:00] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.ClassCastException: net.minecraftforge.fluids.FluidStack cannot be cast to net.minecraft.item.ItemStack
        at com.raoulvdberge.refinedstorage.apiimpl.storage.disk.StorageDiskItem.insert(StorageDiskItem.java:24) ~[StorageDiskItem.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.node.diskdrive.StorageDiskFluidDriveWrapper.insert(StorageDiskFluidDriveWrapper.java:63) ~[StorageDiskFluidDriveWrapper.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.node.diskdrive.StorageDiskFluidDriveWrapper.insert(StorageDiskFluidDriveWrapper.java:18) ~[StorageDiskFluidDriveWrapper.class:?]
        at com.raoulvdberge.refinedstorage.tile.TileController.insertFluid(TileController.java:411) ~[TileController.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeImporter.update(NetworkNodeImporter.java:116) ~[NetworkNodeImporter.class:?]
        at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:23) ~[NetworkNodeListener.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_344_NetworkNodeListener_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[07:36:00] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /minecraft/./crash-reports/crash-2018-08-08_07.36.00-server.txt
[07:36:00] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[07:36:00] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[07:36:00] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[07:36:00] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
[07:36:00] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/ExtraUtils2_Quarry_Dim
[07:36:00] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/nc_wasteland
[07:36:00] [Server thread/INFO] [FML]: Unloading dimension 0
[07:36:00] [Server thread/INFO] [FML]: Unloading dimension -9999
[07:36:00] [Server thread/INFO] [FML]: Unloading dimension 4598
[07:36:00] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -30
[07:36:00] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -29
[07:36:00] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -31
[07:36:00] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -28
[07:36:00] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by gigabit101** [comment] 2018-08-12 16:11
Dupe of #154

**Closed as completed by gigabit101** 2018-08-12 16:11 UTC
